### PR TITLE
Add support for durative-actions

### PR DESCRIPTION
**Pull request by franzlst**
This pull request rewrites many parts of `pddl.py`. The changes are probably not backward compatible. For this, the following features are added:

* No more distinguish between precondition_pos and *_neg, but new class `Goal` that allows to nest `Goal`s with all possible operators: and, or,  not, imply, exits, ...
* Similar for effect: New class `Effect` with operators: and, not, when,  forall, ...
* Support for `durative-action`:
  * with goal operators at start, at end, over all
  * with effect operators at start, at end
  * support for durations
* probably some more things :-)

### CODE REVIEW

**Comment by hfoffani** [comment]
At this point I don't mind too much about backward compatibility.
I'm definitely going to merge it but I also want to add docs, examples and tests (these are on me).
Thanks a lot for your contribution!

**Comment by fmrico** [comment]
Hi @hfoffani and @franzlst ,

Was this PR merged? I think it's a good contribution

Best

**Comment by franzlst** [comment]
It has not been merged yet. I would still be willing to help, though it's @hfoffani turn now!

**Comment by hfoffani** [comment]
I do agree this is a great PR and I'm more than thankful to Franz. At this time I'm more on the apologizing side rather than gratitude.

My main concern (almost an excuse, right now) are the examples and the loss of sync with the dotnet implementation. But maybe I can think of a workaround, apply this PR for once, so people can benefit from this at last.

I'll get on this again tonight.

**Comment by hfoffani** [comment]
Merge done!
I will deal with the other details tomorrow, first and foremost the due acknowledgment.
Thanks a lot and apologies for taking so much time with this.

**Pull request merged**
